### ISSUE TITLE
Connection freezes with websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason

### ISSUE THREAD

**Issue by ihoru** [Brads3290/toggl_webhooks#5]
After an hour of work I get this error:
```
Traceback (most recent call last):
  File "/home/webmaster/apps/toggl_webhooks/ENV/lib/python3.8/site-packages/websockets/protocol.py", line 827, in transfer_data
    message = await self.read_message()
  File "/home/webmaster/apps/toggl_webhooks/ENV/lib/python3.8/site-packages/websockets/protocol.py", line 895, in read_message
    frame = await self.read_data_frame(max_size=self.max_size)
  File "/home/webmaster/apps/toggl_webhooks/ENV/lib/python3.8/site-packages/websockets/protocol.py", line 971, in read_data_frame
    frame = await self.read_frame(max_size)
  File "/home/webmaster/apps/toggl_webhooks/ENV/lib/python3.8/site-packages/websockets/protocol.py", line 1047, in read_frame
    frame = await Frame.read(
  File "/home/webmaster/apps/toggl_webhooks/ENV/lib/python3.8/site-packages/websockets/framing.py", line 105, in read
    data = await reader(2)
  File "/usr/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/webmaster/apps/toggl_webhooks/toggl_webhooks.py", line 101, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/webmaster/apps/toggl_webhooks/toggl_webhooks.py", line 50, in main
    await tc.run(handle_os_signals=True)
  File "/home/webmaster/apps/toggl_webhooks/togglws/client.py", line 207, in __aexit__
    await self.close()
  File "/home/webmaster/apps/toggl_webhooks/togglws/client.py", line 50, in close
    await self.__ws_client.close()
  File "/home/webmaster/apps/toggl_webhooks/togglws/socket.py", line 290, in close
    await self.__run_ws_task
  File "/home/webmaster/apps/toggl_webhooks/togglws/socket.py", line 416, in __run_ws
    next_msg = next_msg_task.result()
  File "/home/webmaster/apps/toggl_webhooks/togglws/socket.py", line 440, in __ws_recv
    msg = await self.__ws.recv()
  File "/home/webmaster/apps/toggl_webhooks/ENV/lib/python3.8/site-packages/websockets/protocol.py", line 509, in recv
    await self.ensure_open()
  File "/home/webmaster/apps/toggl_webhooks/ENV/lib/python3.8/site-packages/websockets/protocol.py", line 803, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 1006 (connection closed abnormally [internal]), no reason
```

The script keep working, exception doesn't stop it for some reason, but no updates are being received since this moment.

Any ideas how to solve it? I guess Toggl's server tries to kill stalled connections (connection which only send "ping" during last 30-40 minutes).

**Comment by Brads3290** [comment]
My (admittedly very brief) research lead me to this, which might be promising: https://stackoverflow.com/questions/54101923/1006-connection-closed-abnormally-error-with-python-3-7-websockets

The answers there seem to suggest a client-side problem, which is interesting. I assumed we'd run into some kind of trouble with Toggl trying to kick us off the long-running websocket, but maybe that isn't what's happening.

I think the next things to do are:
 - Have the socket (or a new socket, if the existing object is in a bad state) try to reconnect when it fails like this
 - After that we can try to sort out the root cause and fix that, in case it's not Toggl's end.

I'll try to work on this over the weekend.

**Comment by ihoru** [comment]
Great! Thanks!
I couldn't even figure out why the program is not terminated, so I didn't know where to start from...
On production I made script restart every 30 minutes to see if it helps :)

**Comment by Brads3290** [comment]
Update: I left the Toggl web app open while I was working and it looks like the web app also naturally reconnects the socket after around an hour:
![image](https://user-images.githubusercontent.com/8080871/113391247-f3f6e980-93de-11eb-814f-fef743053f8e.png)

Looks like this is by Toggl's design after all, so we'll have to replicate the same functionality.

**Comment by Brads3290** [comment]
..and I accidentally hit the wrong button. Ignore the close thing.

**Comment by ihoru** [comment]
So we should simply implement the same reconnection mechanism as well :)
It was smart to check it in this way :+1:

**Comment by Brads3290** [comment]
@ihoru I think this is fixed now. I'll test it as I work today. Could you please let me know how you go too?

**Comment by Brads3290** [comment]
Here's what I get after an hour of operation. I think it works!

```
2021-04-05 11:59:41,775 (toggl_webhooks.py:32) DEBUG: Loading config..
2021-04-05 11:59:41,775 (socket.py:504) DEBUG: Connecting to wss://track.toggl.com/stream..
2021-04-05 11:59:42,015 (socket.py:279) DEBUG: Opened TogglSocket.
2021-04-05 11:59:42,015 (toggl_webhooks.py:40) DEBUG: Configuring hooks..
2021-04-05 11:59:42,015 (toggl_webhooks.py:49) INFO: Listening for events.. Press CTRL+C to stop
2021-04-05 11:59:42,016 (client.py:148) DEBUG: Initialising TogglClient..
2021-04-05 11:59:42,016 (socket.py:369) DEBUG: Authenticating with Toggl server.. : wss://track.toggl.com/stream (token: 4f****************************94)
2021-04-05 11:59:42,224 (socket.py:518) DEBUG: Received: {"session_id":"0e743d9acb5c21ee15851cdfeb3e90e7a2cf954d"}
2021-04-05 11:59:42,224 (socket.py:394) DEBUG: Successfully authenticated with Toggl server.
2021-04-05 11:59:42,224 (socket.py:305) DEBUG: TogglSocket now listening for messages.
2021-04-05 11:59:42,224 (client.py:89) DEBUG: Starting listener task..
2021-04-05 11:59:42,224 (client.py:66) DEBUG: Running Toggl client..
2021-04-05 11:59:42,224 (socket.py:518) DEBUG: Received: {"type":"ping"}
2021-04-05 11:59:54,251 (socket.py:518) DEBUG: Received: {"type":"ping"}

...

2021-04-05 12:59:26,344 (socket.py:518) DEBUG: Received: {"type":"ping"}
2021-04-05 12:59:39,289 (socket.py:518) DEBUG: Received: {"type":"ping"}
2021-04-05 12:59:42,027 (socket.py:465) DEBUG: Socket disconnected by server. Attempting to reconnect..
2021-04-05 12:59:42,028 (socket.py:504) DEBUG: Connecting to wss://track.toggl.com/stream..
2021-04-05 12:59:42,282 (socket.py:369) DEBUG: Authenticating with Toggl server.. : wss://track.toggl.com/stream (token: 4f****************************94)
2021-04-05 12:59:42,489 (socket.py:518) DEBUG: Received: {"session_id":"65b5729ef0517693ca179b1b966c11741a0d2bf3"}
2021-04-05 12:59:42,489 (socket.py:394) DEBUG: Successfully authenticated with Toggl server.
2021-04-05 12:59:42,489 (socket.py:437) DEBUG: Waiting for 0.0 seconds before retry..
2021-04-05 12:59:42,489 (socket.py:518) DEBUG: Received: {"type":"ping"}
2021-04-05 12:59:47,541 (socket.py:518) DEBUG: Received: {"type":"ping"}
```

Note that this reconnects at 1 hour exactly, after the server closes the connection. In my test, the Toggl web app reconnected at around 58 mins which suggests that Toggl places the responsibility on the _client_ to close the connection and reconnect before the hour, so maybe we should implement additional logic to do that.

**Comment by Brads3290** [comment]
I ran this for around 7 hours today and no issues. At some point I'll put it on a server; It'll be interesting to see how it goes over a period of months/weeks rather than hours.

@ihoru If everything is OK for you, I'll close this issue.

**Comment by ihoru** [comment]
It works fine for me!
Thank you!
